INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('jamesbrown','jamesbrown01@example.co.uk','password1','TILTED TOWERS',280,515);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('emilywhite','emilywhite02@example.co.uk','password2','PLEASANT PARK',180,301);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('michaeljohnson','michaeljohnson03@example.co.uk','password3','RETAIL ROW',720,570);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('sarahwilliams','sarahwilliams04@example.co.uk','password4','SALTY SPRINGS',570,636);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('davidjones','davidjones05@example.co.uk','password5','DUSTY DIVOT',570,486);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('laurabrown','laurabrown06@example.co.uk','password6','LOOT LAKE',400,390);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('robertjames','robertjames07@example.co.uk','password7','LAZY LINKS',540,226);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('samanthagarcia','samanthagarcia08@example.co.uk','password8','RISKY REELS',760,205);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('danielmartin','danielmartin09@example.co.uk','password9','TOMATO TEMPLE',670,340);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('ashleythomas','ashleythomas10@example.co.uk','password10','LONELY LODGE',870,433);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('christophermoore','christophermoore11@example.co.uk','password11','PARADISE PALMS',870,767);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('meganclark','meganclark12@example.co.uk','password12','FATAL FIELDS',500,807);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('anthonymartinez','anthonymartinez13@example.co.uk','password13','GREASY GROVE',180,635);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('amandalee','amandalee14@example.co.uk','password14','SHIFTY SHAFTS',280,695);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('nicholasrobinson','nicholasrobinson15@example.co.uk','password15','FLUSH FACTORY',280,835);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('victorhernandez','victorhernandez16@example.co.uk','password16','LUCKY LANDING',400,950);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('oliviawalker','oliviawalker17@example.co.uk','password17','WAILING WOODS',820,287);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('markyoung','markyoung18@example.co.uk','password18','HAUNTED HILLS',156,169);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('rachelking','rachelking19@example.co.uk','password19','JUNK JUNCTION',189,110);
INSERT INTO users (username,email,password,address,latitude,longitude) VALUES('stevenwright','stevenwright20@example.co.uk','password20','SNOBBY SHORES',69,467);

INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(1,TO_DATE('2015-04-12','YYYY-MM-DD'),'Emily','Brown','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(1,TO_DATE('2018-09-30','YYYY-MM-DD'),'Thomas','Brown','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(2,TO_DATE('2017-07-21','YYYY-MM-DD'),'Chloe','White','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(3,TO_DATE('2012-01-05','YYYY-MM-DD'),'Luke','Johnson','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(3,TO_DATE('2014-11-18','YYYY-MM-DD'),'Olivia','Johnson','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(3,TO_DATE('2019-06-02','YYYY-MM-DD'),'Harry','Johnson','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(4,TO_DATE('2016-03-27','YYYY-MM-DD'),'Isabella','Williams','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(5,TO_DATE('2013-12-10','YYYY-MM-DD'),'Jack','Jones','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(5,TO_DATE('2018-05-05','YYYY-MM-DD'),'Sophie','Jones','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(6,TO_DATE('2011-08-14','YYYY-MM-DD'),'Mia','Brown','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(6,TO_DATE('2014-02-23','YYYY-MM-DD'),'Joshua','Brown','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(6,TO_DATE('2020-12-01','YYYY-MM-DD'),'Ella','Brown','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(7,TO_DATE('2019-09-09','YYYY-MM-DD'),'Alexander','James','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(8,TO_DATE('2012-06-15','YYYY-MM-DD'),'Grace','Garcia','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(8,TO_DATE('2015-10-30','YYYY-MM-DD'),'Benjamin','Garcia','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(9,TO_DATE('2010-11-22','YYYY-MM-DD'),'Lily','Martin','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(9,TO_DATE('2013-03-03','YYYY-MM-DD'),'William','Martin','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(9,TO_DATE('2017-07-07','YYYY-MM-DD'),'Ella','Martin','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(10,TO_DATE('2016-04-01','YYYY-MM-DD'),'Daniel','Thomas','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(11,TO_DATE('2013-09-19','YYYY-MM-DD'),'Sienna','Moore','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(11,TO_DATE('2019-02-14','YYYY-MM-DD'),'Leo','Moore','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(12,TO_DATE('2014-12-25','YYYY-MM-DD'),'Eva','Clark','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(13,TO_DATE('2011-05-11','YYYY-MM-DD'),'Mason','Martinez','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(13,TO_DATE('2015-08-29','YYYY-MM-DD'),'Scarlett','Martinez','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(13,TO_DATE('2018-01-20','YYYY-MM-DD'),'Ethan','Martinez','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(14,TO_DATE('2012-02-02','YYYY-MM-DD'),'Abigail','Lee','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(14,TO_DATE('2017-11-11','YYYY-MM-DD'),'Samuel','Lee','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(15,TO_DATE('2019-05-05','YYYY-MM-DD'),'Emily','Robinson','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(16,TO_DATE('2010-10-10','YYYY-MM-DD'),'Noah','Hernandez','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(16,TO_DATE('2014-04-04','YYYY-MM-DD'),'Zoe','Hernandez','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(16,TO_DATE('2018-08-08','YYYY-MM-DD'),'Caleb','Hernandez','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(17,TO_DATE('2013-03-03','YYYY-MM-DD'),'Hannah','Walker','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(17,TO_DATE('2016-06-06','YYYY-MM-DD'),'Ryan','Walker','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(18,TO_DATE('2017-07-07','YYYY-MM-DD'),'Zara','Young','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(19,TO_DATE('2012-12-12','YYYY-MM-DD'),'Oliver','King','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(19,TO_DATE('2015-05-15','YYYY-MM-DD'),'Charlotte','King','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(20,TO_DATE('2011-01-01','YYYY-MM-DD'),'Evelyn','Wright','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(20,TO_DATE('2014-04-04','YYYY-MM-DD'),'Logan','Wright','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(20,TO_DATE('2018-08-08','YYYY-MM-DD'),'Madison','Wright','F');

INSERT INTO data (child_id,location,latitude,longitude) VALUES(1,'PLEASANT PARK',180,301);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(2,'DUSTY DIVOT',570,486);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(3,'RETAIL ROW',720,570);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(4,'TILTED TOWERS',280,515);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(5,'LOOT LAKE',400,390);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(6,'SALTY SPRINGS',570,636);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(7,'LAZY LINKS',540,226);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(8,'TOMATO TEMPLE',670,340);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(9,'RISKY REELS',760,205);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(10,'WAILING WOODS',820,287);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(11,'LONELY LODGE',870,433);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(12,'PARADISE PALMS',870,767);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(13,'FATAL FIELDS',500,807);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(14,'GREASY GROVE',180,635);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(15,'SHIFTY SHAFTS',280,695);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(16,'FLUSH FACTORY',280,835);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(17,'LUCKY LANDING',400,950);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(18,'HAUNTED HILLS',156,169);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(19,'JUNK JUNCTION',189,110);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(20,'SNOBBY SHORES',69,467);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(21,'TILTED TOWERS',280,515);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(22,'PLEASANT PARK',180,301);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(23,'DUSTY DIVOT',570,486);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(24,'RETAIL ROW',720,570);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(25,'LOOT LAKE',400,390);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(26,'SALTY SPRINGS',570,636);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(27,'LAZY LINKS',540,226);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(28,'TOMATO TEMPLE',670,340);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(29,'RISKY REELS',760,205);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(30,'WAILING WOODS',820,287);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(31,'LONELY LODGE',870,433);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(32,'PARADISE PALMS',870,767);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(33,'FATAL FIELDS',500,807);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(34,'GREASY GROVE',180,635);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(35,'SHIFTY SHAFTS',280,695);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(36,'FLUSH FACTORY',280,835);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(37,'LUCKY LANDING',400,950);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(38,'HAUNTED HILLS',156,169);
INSERT INTO data (child_id,location,latitude,longitude) VALUES(39,'JUNK JUNCTION',189,110);

INSERT INTO accidents (latitude,longitude,type,description) VALUES(189,110,'Explosive Zone','Grenade launcher fire reported in area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(156,169,'Sniper Activity','Sniper shots detected in vicinity');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(180,301,'Building Demolition','Multiple structures being destroyed');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(69,467,'Trap Field','Area littered with spike traps');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(180,635,'Vehicle Chaos','Out of control shopping carts in area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(280,695,'Storm Approaching','Storm circle closing in on location');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(69,775,'Unstable Ground','Terrain showing signs of collapse');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(280,835,'Heavy Combat','Intense firefight ongoing');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(400,950,'Supply Drop Zone','Multiple supply crates falling from sky');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(500,807,'Rocket Launcher Zone','Rocket launcher activity detected');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(570,636,'Storm Damage','Area affected by storm circle');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(570,486,'Crossfire Zone','Multiple teams engaged in combat');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(400,390,'Water Hazard','Dangerous currents in lake area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(280,515,'Explosive Barrels','Unstable fuel barrels scattered around');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(760,205,'Falling Debris','Structures collapsing in vicinity');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(820,287,'Forest Fire','Smoke and flames spreading through trees');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(670,340,'Toxic Gas','Stink bomb residue contaminating area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(870,433,'Rift Instability','Unstable rifts opening randomly');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(720,570,'Shopping Mayhem','Runaway shopping carts everywhere');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(870,767,'Sandstorm','Visibility severely reduced by sand');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(400,200,'Bounce Pad Malfunction','Broken bounce pads launching unexpectedly');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(600,300,'Llama Stampede','Wild llamas running through area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(300,400,'Booby Trap Zone','Hidden traps planted throughout');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(450,600,'Campfire Smoke','Thick smoke reducing visibility');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(150,750,'Ice Storm','Slippery ice covering all surfaces');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(750,150,'High Winds','Strong gusts affecting movement');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(350,350,'Construction Zone','Unsafe building activity ongoing');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(550,550,'Friendly Fire Risk','Team conflicts in progress');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(200,200,'Dense Foliage','Limited visibility due to overgrowth');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(800,800,'Portal Anomaly','Rifts behaving unpredictably');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(100,900,'Contaminated Area','Toxic mushrooms spread throughout');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(900,100,'Impulse Grenade Testing','Active grenade testing in area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(250,750,'Shield Generator Leak','Malfunctioning shield technology');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(750,250,'Dance Battle Zone','Chaotic emote battles blocking paths');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(500,500,'Medical Emergency','First aid stations overwhelmed');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(650,350,'Launch Pad Chaos','Multiple launch pads firing randomly');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(350,650,'Healing Station Overload','Medical supplies depleted');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(450,450,'Fort Construction','Massive fort building blocking area');