UPDATE users SET address = 'TILTED TOWERS', latitude = 387, longitude = 573 WHERE username = 'jamesbrown';
UPDATE users SET address = 'PLEASANT PARK', latitude = 304, longitude = 278 WHERE username = 'emilywhite';
UPDATE users SET address = 'RETAIL ROW', latitude = 875, longitude = 515 WHERE username = 'michaeljohnson';
UPDATE users SET address = 'SALTY SPRINGS', latitude = 571, longitude = 580 WHERE username = 'sarahwilliams';
UPDATE users SET address = 'DUSTY DIVOT', latitude = 604, longitude = 438 WHERE username = 'davidjones';

INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(1,TO_DATE('2015-04-12','YYYY-MM-DD'),'Emily','Brown','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(1,TO_DATE('2018-09-30','YYYY-MM-DD'),'Thomas','Brown','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(2,TO_DATE('2017-07-21','YYYY-MM-DD'),'Chloe','White','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(3,TO_DATE('2012-01-05','YYYY-MM-DD'),'Luke','Johnson','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(3,TO_DATE('2014-11-18','YYYY-MM-DD'),'Olivia','Johnson','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(3,TO_DATE('2019-06-02','YYYY-MM-DD'),'Harry','Johnson','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(4,TO_DATE('2016-03-27','YYYY-MM-DD'),'Isabella','Williams','F');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(5,TO_DATE('2013-12-10','YYYY-MM-DD'),'Jack','Jones','M');
INSERT INTO children (user_id,birthdate,first_name,last_name,gender) VALUES(5,TO_DATE('2018-05-05','YYYY-MM-DD'),'Sophie','Jones','F');

INSERT INTO data (child_id, location, latitude, longitude) VALUES (1, 'PLEASANT PARK', 261, 324);
INSERT INTO data (child_id, location, latitude, longitude) VALUES (2, 'DUSTY DIVOT', 603, 503);
INSERT INTO data (child_id, location, latitude, longitude) VALUES (3, 'RETAIL ROW', 762, 545);
INSERT INTO data (child_id, location, latitude, longitude) VALUES (4, 'TILTED TOWERS', 405, 494);
INSERT INTO data (child_id, location, latitude, longitude) VALUES (5, 'LOOT LAKE', 448, 318);
INSERT INTO data (child_id, location, latitude, longitude) VALUES (6, 'SALTY SPRINGS', 608, 631);
INSERT INTO data (child_id, location, latitude, longitude) VALUES (7, 'LAZY LINKS', 556, 205);
INSERT INTO data (child_id, location, latitude, longitude) VALUES (8, 'TOMATO TEMPLE', 684, 326);
INSERT INTO data (child_id, location, latitude, longitude) VALUES (9, 'RISKY REELS', 774, 218);

INSERT INTO accidents (latitude,longitude,type,description) VALUES(189,110,'Explosive Zone','Grenade launcher fire reported in area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(156,169,'Sniper Activity','Sniper shots detected in vicinity');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(180,301,'Building Demolition','Multiple structures being destroyed');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(69,467,'Trap Field','Area littered with spike traps');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(180,635,'Vehicle Chaos','Out of control shopping carts in area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(280,695,'Storm Approaching','Storm circle closing in on location');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(69,775,'Unstable Ground','Terrain showing signs of collapse');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(280,835,'Heavy Combat','Intense firefight ongoing');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(400,950,'Supply Drop Zone','Multiple supply crates falling from sky');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(500,807,'Rocket Launcher Zone','Rocket launcher activity detected');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(570,636,'Storm Damage','Area affected by storm circle');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(570,486,'Crossfire Zone','Multiple teams engaged in combat');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(400,390,'Water Hazard','Dangerous currents in lake area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(280,515,'Explosive Barrels','Unstable fuel barrels scattered around');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(760,205,'Falling Debris','Structures collapsing in vicinity');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(820,287,'Forest Fire','Smoke and flames spreading through trees');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(670,340,'Toxic Gas','Stink bomb residue contaminating area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(870,433,'Rift Instability','Unstable rifts opening randomly');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(720,570,'Shopping Mayhem','Runaway shopping carts everywhere');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(870,767,'Sandstorm','Visibility severely reduced by sand');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(400,200,'Bounce Pad Malfunction','Broken bounce pads launching unexpectedly');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(600,300,'Llama Stampede','Wild llamas running through area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(300,400,'Booby Trap Zone','Hidden traps planted throughout');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(450,600,'Campfire Smoke','Thick smoke reducing visibility');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(150,750,'Ice Storm','Slippery ice covering all surfaces');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(750,150,'High Winds','Strong gusts affecting movement');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(350,350,'Construction Zone','Unsafe building activity ongoing');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(550,550,'Friendly Fire Risk','Team conflicts in progress');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(200,200,'Dense Foliage','Limited visibility due to overgrowth');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(800,800,'Portal Anomaly','Rifts behaving unpredictably');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(100,900,'Contaminated Area','Toxic mushrooms spread throughout');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(900,100,'Impulse Grenade Testing','Active grenade testing in area');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(250,750,'Shield Generator Leak','Malfunctioning shield technology');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(750,250,'Dance Battle Zone','Chaotic emote battles blocking paths');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(500,500,'Medical Emergency','First aid stations overwhelmed');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(650,350,'Launch Pad Chaos','Multiple launch pads firing randomly');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(350,650,'Healing Station Overload','Medical supplies depleted');
INSERT INTO accidents (latitude,longitude,type,description) VALUES(450,450,'Fort Construction','Massive fort building blocking area');